# file: compose.yaml
# description: Compose stack to launch graven database
#
# @author: Derek Garcia
name: graven
services:

  # SQL Database
  mysql:
    container_name: graven_database
    image: mysql:8.4.3
    env_file:
      - .env
    volumes:
      - ./ddl:/docker-entrypoint-initdb.d
      - graven_db:/var/lib/mysql
    ports:
      - ${EXTERNAL_PORT:-3306}:3306
    networks:
      graven:

# Create a named persistent volume
volumes:
  graven_db:

# Create custom network for other containers to attach to
networks:
  graven: