name: Release

on:
  release:
    types:
      - published

jobs:
  image:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.1.0

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.15.0
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}
            ghcr.io/${{ github.repository }}:latest

  sbom:
    runs-on: ubuntu-24.04
    permissions:
      actions: read
      contents: write
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Generate SPDX SBOM
        uses: anchore/sbom-action@v0.18.0
        with:
          path: ./graven/
          format: spdx
          artifact-name: graven.sbom.spdx

      - name: Generate CycloneDX SBOM
        uses: anchore/sbom-action@v0.18.0
        with:
          path: ./graven/
          format: cyclonedx-json
          artifact-name: graven.sbom.cdx.json